### ISSUE TITLE
Using _episodes_es and _episodes in a single repository

### ISSUE THREAD

**Issue by rgaiacs** [Carpentries-ES/board#10]
Is possible to host the translation in the same repository as I will explain below.

# Add _episodes_es

In `_config.yml`, change

~~~
# Specify that things in the episodes collection should be output.
collections:
  episodes:
    output: true
    permalink: /:path/
  extras:
    output: true

# Set the default layout for things in the episodes collection.
defaults:
  - values:
      root: ..
  - scope:
      path: ""
      type: episodes
    values:
      layout: episode
~~~

to

~~~
# Specify that things in the episodes collection should be output.
collections:
  episodes:
    output: true
    permalink: /en/:path/
  episodes_es:
    output: true
    permalink: /es/:path/
  extras:
    output: true
    permalink: /en/:path/
  extras_es:
    output: true
    permalink: /es/:path/

# Set the default layout for things in the episodes collection.
defaults:
  - values:
      root: ..
  - scope:
      path: ""
      type: episodes
    values:
      layout: episode
  - scope:
      path: ""
      type: episodes_es
    values:
      layout: es/episode
~~~

# Translate `_layouts` and `_includes`

`_layouts` and `_includes` are special directories to Jekyll so we can't have `_layouts_es` and `_includes_es`. I'm almost 100% sure that you can have `_layouts/en` and `_layouts/es` without problem. **All** the files in `_layouts` and `_includes` need to be translated, for example `_layouts/episode.html` must be translated to `_layouts/es/episode.html`.

# Add Spanish to the navigation bar

Change `_includes/navbar.html` to include a link to the Spanish version.

# Downside

GitHub doesn't allow users to tag their pull request and issues and by consequence there is no way to lower the number of email that maintainers receive. Except for it, this would be a good solution.

# Procedure

This changes need to be tested with a lesson and later some of the changes need to go to https://github.com/swcarpentry/styles. I can't do the changes but I can port it to styles.

**Comment by orchid00** [comment]
Thanks @rzayas 
@rgaiacs @map0logo @agbeltran @jmbarrios 
I have a doubt, when translating index.md readme.md etc 
should be create a new file? indes_es.md? or replace the original ?

**Comment by agbeltran** [comment]
Hi @orchid00 
I believe we should keep both, as this solution is to have the two versions (English and Spanish, and potentially other translations too), co-existing in the single repository. 
@rgaiacs  should be able to clarify. 
Thanks!

**Comment by rgaiacs** [comment]
> I have a doubt, when translating index.md readme.md etc
> should be create a new file? indes_es.md? or replace the original ?

In this case, you will want to have a `es` directory to store the files.

**Comment by rgaiacs** [comment]
And we would want to move `index.md` to `en/index.md` to not give the wrong impression that it is a first class and `es` is a second class.

**Comment by jmbarrios** [comment]
@orchid00 I agree with @rgaiacs about make a new directory for `index.md`, and all those files.

**Comment by orchid00** [comment]
OK I will punt index and extra files in the ES folder. I hope the infrastructure meeting was productive. Thanks to all you are part of this discussion.

**Comment by rgaiacs** [comment]
> All the original files, english site, must not be moved to another location.

Why not? Git keep track of change in the name of files.

> The solution must be minimal disruptive to preserve the original site.

Can you clarify this?

> I hope the infrastructure meeting was productive. 

It was. I give some suggestions for people to think about.

**Comment by jmbarrios** [comment]
@rgaiacs 

> Why not? Git keep track of change in the name of files.

Certainly git keeps files history but when we try incorporate the main repository in the translated one, we have to do two steps: first pull the original one than update moved files.

> Can you clarify this?

The English repository constantly  receives fixes in content so we have to be able to incoporate those. So is preferred have similar structure as the English site

**Comment by rgaiacs** [comment]
I'm closing this because for now we will be doing the translation on their own repository.
