### ISSUE TITLE
Using _episodes_es and _episodes in different repositories

### ISSUE THREAD

**Issue by rgaiacs** [Carpentries-ES/board#11]
This is a alternative to #10.

# Replace _episodes with _episodes_es

In `_config.yml`, change

~~~
# Specify that things in the episodes collection should be output.
collections:
  episodes:
    output: true
    permalink: /:path/
  extras:
    output: true

# Set the default layout for things in the episodes collection.
defaults:
  - values:
      root: ..
  - scope:
      path: ""
      type: episodes
    values:
      layout: episode
~~~

to

~~~
# Specify that things in the episodes collection should be output.
collections:
  episodes_es:
    output: true
    permalink: /:path/
  extras:
    output: true

# Set the default layout for things in the episodes collection.
defaults:
  - values:
      root: ..
  - scope:
      path: ""
      type: episodes_es
    values:
      layout: episode
~~~

# Translate `_layouts` and `_includes`

You need to replace `episodes` with `episodes_es` in all for-loops.

**Comment by jmbarrios** [comment]
@rgaiacs Do you propose to have more than a one `_config.yml` file?

It is possible: new command on `Makefile` to build the translated site

**Comment by rgaiacs** [comment]
> Do you propose to have more than a one `_config.yml` file?

No. You should have only one `_config.yml`.

> It is possible: new command on Makefile to build the translated site

You won't need a new command.

**Comment by rgaiacs** [comment]
I'm closing this because for now we will be doing the translation on their own repository.
