### ISSUE TITLE
Please make a deadline for a decision about where files will be!!!

### ISSUE THREAD

**Issue by rgaiacs** [Carpentries-ES/board#15]
The conversation about translation is starting to spread among many places, e.g. https://github.com/swcarpentry/git-novice/pull/457. **Please make a decision ASAP** for which workflow you want to follow in the first semester of 2018 and we can review it in June.

**Comment by orchid00** [comment]
@map0logo what are the options?

**Comment by orchid00** [comment]
If there is no other opinion or opposition.

Let's keep all translated files in the folder _episodes_es for each lesson. Does that answer your question @rgaiacs ?

**Comment by rgaiacs** [comment]
> Let's keep all translated files in the folder _episodes_es for each lesson.

Please see https://github.com/Carpentries-ES/board/issues/14#issuecomment-352282298.

> Does that answer your question 

You need to resolve https://github.com/Carpentries-ES/board/issues/14#issuecomment-352282298. This is what is blocking https://github.com/swcarpentry/git-novice/pull/457.

**Comment by raynamharris** [comment]
Can we close this issue @fmichonneau @rgaiacs @orchid00 ? This seems to be resolved .

**Comment by rgaiacs** [comment]
We will be storing the translation on their own repository for now.
