### ISSUE TITLE
Traducir o no traducir archivos en Git

### ISSUE THREAD

**Issue by raynamharris** [Carpentries-ES/board#18]
@map0logo hizo un buen punto en committ https://github.com/swcarpentry/git-novice-es/commit/b25077f995958d1dddb22bf6fdafab9a8bf399f6

Esto ilustra la complejidad del problema. Leyenda: palabra española = palabra en inglés. Las palabras en negrita se usan en las clases de español.

![ejemplomotivador-01](https://user-images.githubusercontent.com/7544197/37537379-18399372-292c-11e8-94fa-e7e626de74b3.png)

De acuerdo con Convenciones_Traduccion.md, los nombres de archivos y directorios no se deben traducir. Sin embargo, para esta lección, no se descargan archivos, y todos son creados por los participantes durante el taller. Creo que vale la pena considerar la traducción de estos nombres de archivos y directorios.

¿Qué piensas?
[![](https://api.gh-polls.com/poll/01C8QZW7NEZ4VRDZV9VSVBG3T7/Traducir%20todos%20los%20nombres)](https://api.gh-polls.com/poll/01C8QZW7NEZ4VRDZV9VSVBG3T7/Traducir%20todos%20los%20nombres/vote)
[![](https://api.gh-polls.com/poll/01C8QZW7NEZ4VRDZV9VSVBG3T7/Traducir%20algunos%20de%20los%20nombres)](https://api.gh-polls.com/poll/01C8QZW7NEZ4VRDZV9VSVBG3T7/Traducir%20algunos%20de%20los%20nombres/vote)
[![](https://api.gh-polls.com/poll/01C8QZW7NEZ4VRDZV9VSVBG3T7/Traducir%20ninguno%20de%20los%20nombres)](https://api.gh-polls.com/poll/01C8QZW7NEZ4VRDZV9VSVBG3T7/Traducir%20ninguno%20de%20los%20nombres/vote)

**Comment by orchid00** [comment]
@raynamharris is it possible to move this to the Git repo? or are we going to loose the votes?

**Comment by raynamharris** [comment]
Ah, sorry, I forgot this was open. There was a lot of votes (many non-verbal) for "not changing the name". Let's go ahead and close.
