### ISSUE TITLE
Transifex loose translated strings when word change

### ISSUE THREAD

**Issue by rgaiacs** [Carpentries-ES/board#2]
# How to reproduce

**You will need a Transifex account** and the [Python client installed](https://docs.transifex.com/client/installing-the-client).

1. Clone (locally) any Software Carpentry or Data Carpentry lesson.
2. Change the current directory to the root of the lesson.
3. Run `tx init`
4. Run `tx set --auto-local -r your-transifex-project.XX "_episodes_<lang>/XX.md" --source-lang en --type GITHUBMARKDOWN --source-file _episodes/XX-some-lesson-name.md --execute`. **Keep `<lang>` unchaged**.
5. Run `tx push -s -t`.
6. Go to Transifex and translate the 5 first strings.
7. Edit _episodes/XX-some-lesson-name.md. For example, change the value of `title` on the YAML header and introduce some typos at the first few paragraphs.
8. Run `tx push -s -t`  **Yes, this is the same command on item 5.**
9. Go to Transifex and look what happen with the 5 first strings.

# Expected behaviour

Keep part of the translation.

# Current behaviour

Any string that change has the translation cleaned.

For example, if the string "Introducing the Shell" was translated to "Presentación de la Shell" but later changed to "Introducing Bash" the translation is **completely** removed. The problem is worse because Transifex split the strings to be translated by paragraph. If we translate

~~~
They could do the last of these in different ways,
including direct brain-computer interfaces and speech recognition, using systems such as Alexa or Google Home.
While such hardware interfaces are becoming more commonplace, most interaction is still
done using screens, mice, touchpads and keyboards.
Although most modern desktop operating systems communicate with their human users by
means of windows, icons and pointers, these software technologies didn't become
widespread until the 1980s. The roots of such *graphical user interfaces* go back
to Doug Engelbart's work in the 1960s, which you can see in what has been
called "[The Mother of All Demos](http://www.youtube.com/watch?v=a11JDLBXtPQ)".
~~~

but later we change the URL from `http://www.youtube.com/watch?v=a11JDLBXtPQ` to `https://youtu.be/a11JDLBXtPQ` the translation of the full paragraph will be lost even if we didn't need to change anything on it but just the link.

**Comment by orchid00** [comment]
Hi @rgaiacs, thanks for bringing this up, I was unaware of this issue. Also, it's my first time using transifex, maybe this is something that @mapologo is already looking into.
Please let me know if you have time to meet, we can discuss what other options we could use.

**Comment by jmbarrios** [comment]
Is this issue still valid?

**Comment by orchid00** [comment]
@jmbarrios maybe this is not relevant anymore, since we will discontinue the use of transifex. But I will let @map0logo reply.

**Comment by rgaiacs** [comment]
It has been decided to drop transifex to translate the content.
