### ISSUE TITLE
Fila o renglón

### ISSUE THREAD

**Issue by LUS24** [Carpentries-ES/board#26]
@orchid00 Definir si se usa fila o renglón para la traducción de row.
Hay criterios mezclados en los archivos de [python-ecology-lesson-es](https://github.com/Carpentries-ES/python-ecology-lesson-es).

**Comment by orchid00** [comment]
ya lo agregue a las convenciones, 
row = fila

**Comment by jmbarrios** [comment]
Yo prefiero renglón, fila es confuso dependiendo del país y contexto

**Comment by orchid00** [comment]
si Juan, sé que prefieres renglón. Pero, he consultado con otros y con google y foros, definitivamente fila es más usado.
