### ISSUE TITLE
traducción 'plotting library'

### ISSUE THREAD

**Issue by NPalopoli** [Carpentries-ES/board#45]
¿Cuál consideran la traducción correcta para "plotting library"?
- biblioteca de graficado
- biblioteca de graficación
- biblioteca de generación de gráficos
- biblioteca de gráficos
- biblioteca de visualización

Mi voto va por la cuarta opción, "biblioteca de gráficos".

**Comment by xmnlab** [comment]
creo que se entiende bien "biblioteca de gráficos" :+1

**Comment by orchid00** [comment]
biblioteca de gráficos

**Comment by orchid00** [comment]
agregado a https://github.com/Carpentries-ES/board/blob/master/Convenciones_Traduccion.md
